imports:
    - { resource: parameters.yml }

services:
    guzzle.http.client:
        class: GuzzleHttp\Client

    app.email_service:
        class:     AppBundle\Services\EmailService
        arguments:
            - '@guzzle.http.client'
            - "@doctrine.orm.entity_manager"
            - %email_service_host%

    app.send_service:
        class:     AppBundle\Services\SendService
        arguments:
            - "@doctrine.orm.entity_manager"
            - '@mailer'
            - %mailer_from%

framework:
    secret: '%secret_key%'
    form: ~
    assets: ~
    templating:
        engines: ['twig']
    serializer:
        enabled: true
        enable_annotations: true

swiftmailer:
    transport:  "%mailer_transport%"
    host:       "%mailer_host%"
    port:       "%mailer_port%"
    encryption: "ssl"
    username:   "%mailer_username%"
    password:   "%mailer_password%"
    spool:     { type: memory }

doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        path:     %kernel.root_dir%/../%database_path%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

