---
- name: Install python-pycurl
  apt: pkg=python-pycurl state=latest

- name: Install PHP 
  apt: name=php5 state=latest force=yes

- name: Intsall PHP packages
  apt: name={{ item }} state=latest force=yes
  with_items:
    - php-apc
    - php5-cli
    - php5-gd
    - php5-curl
    - php5-intl
    - php5-mcrypt
    - php5-sqlite

- name: Configure PHP
  template: src=php_config.ini.j2 dest=/etc/php5/apache2/conf.d/php_config.ini force=yes
